# The Discord bot token
bot_token: ""

# Trigger phrase (case-insensitive)
#
# If one of the users defined in allowed_command_user_ids says this phrase
# exactly (case-insensitive), then the bot will activate
#
# If an empty string or not defined, triggering will be disabled
trigger_phrase: "let's fly to the castle"

# The Discord User IDs that are allowed to run bot commands
allowed_command_user_ids: []

# The path to the audio clip to play before kicking a user
audio_clip_filepath: "audio.mp3"

# If the path to a folder of pictures is provided
# The bot will send `picture_amount` pictures to a user after
# kicking them
picture_folder: ""
picture_amount: 1
# A list of messages to send to the user after the photos
# If no messages are provided, none will be sent
after_picture_messages: []
